### ISSUE TITLE
Final Warning Letter - YSANC005

### ISSUE THREAD

**Issue by SageTertius** [SageTertius/SS_X3_Reports#14]
Example Link: https://github.com/SageTertius/SS_X3_Reports/blob/master/Report%20Examples/Work%20Ethics/All%20letter%20templates%20for%20Sanctions%20and%20Commendations.doc
Example Page No: 6
Report Name: WARNLET
Report Template Link: https://github.com/SageTertius/SS_X3_Reports/blob/master/Report%20Templates/Work%20Ethics/YDISSUMTEMP.rpt
Comment:

**Comment by Quintonsmithy** [comment]
Re-open for Alma to change View

**Comment by RiaanWilk** [comment]
TESTED ON UBA

**Comment by carldek** [comment]
Duplicate
