### ISSUE TITLE
Disciplinary Report - YDISREP

### ISSUE THREAD

**Issue by SageTertius** [SageTertius/SS_X3_Reports#15]
Example Link: https://github.com/SageTertius/SS_X3_Reports/blob/master/Report%20Examples/Work%20Ethics/6.%20Disciplinary%20Mgmt%20Reports.xlsx
Example Page No: 
Report Name: DISREP
Report Template Link:
https://github.com/SageTertius/SS_X3_Reports/blob/master/Report%20Templates/Work%20Ethics/YDISREP.rpt
Comment:

**Comment by Quintonsmithy** [comment]
Re-open for Alma to change View

**Comment by KaltwasserAlma** [comment]
Uploaded to UAT

**Comment by carldek** [comment]
Tested 10.16 Pass
