### ISSUE TITLE
Suspension Pending Investigation - YSANC011

### ISSUE THREAD

**Issue by SageTertius** [SageTertius/SS_X3_Reports#16]
Example Link: https://github.com/SageTertius/SS_X3_Reports/blob/master/Report%20Examples/Work%20Ethics/Suspension%20Pending%20Determination%20of%20Case.docx
Example Page No: 1
Report Name: SUSPLET
Report Template Link: https://github.com/SageTertius/SS_X3_Reports/blob/master/Report%20Templates/Work%20Ethics/YDISSUMTEMP.rpt
Comment: Sanction Sub Report

**Comment by Quintonsmithy** [comment]
Re-open for Alma to change View

**Comment by RiaanWilk** [comment]
TESTED ON UBA

**Comment by carldek** [comment]
Duplicate #3
