### ISSUE TITLE
Onboarding Form: 

### ISSUE THREAD

**Issue by SageTertius** [SageTertius/SS_X3_Reports#27]
Example Link: 
Example Page No: 
Report Type: 
Report Name: 
Comment:

**Comment by RiaanWilk** [comment]
YPERINF         -   NEW EMPLOYEE PROFILE FORM
YPASSSEC      -   PASSWORD SECRECY UNDERTAKING
YPARDEC       -   RELATED PARTIES DECLARATION FORM
YGUAFRM      -   GUARANTOR'S FORM
YFEDMOR      -   FEDERAL MORTGAGE BANK OF NIGERIA
YASSDEC        -   ASSETS DECLARATION FORM
YACCOPN      -   INDIVIDUAL ACCOUNT OPENING FORM
YACCCHK       -   NEW HIRE (UBA STAFF) ACCOUNT OPENING CHECKLIST

CHECKED AND UPLOADED
