### ISSUE TITLE
Interview Rating Forms

### ISSUE THREAD

**Issue by SageTertius** [SageTertius/SS_X3_Reports#28]
Example Link: https://github.com/SageTertius/SS_X3_Reports/tree/master/Report%20Examples/New%20Hire%20Documents/Interview%20Rating%20Forms
Example Page No: Multiple Documents
Report Type: Crystal Report
Report Name/s: 
1. YINTRATGM (For General Managers)
2. YINTRATMM (For Middle Managers)
3. YINTRATOF (For Officers)
4. YINTRATSM (For Senior Managers)
https://github.com/SageTertius/SS_X3_Reports/tree/master/Report%20Templates/HR%20Onboarding/Interview%20Rating%20Forms
Comment: Multiple Crystal reports based on the different templates

**Comment by Quintonsmithy** [comment]
Uploaded to UBA UAT for testing.
The Reports prints big open areas when it prints to PDF

**Comment by RiaanWilk** [comment]
Redone YINTRAPMM, uploaded to GitHub...
