### ISSUE TITLE
Former Employment Reference Report - YFOREMPCOV

### ISSUE THREAD

**Issue by SageTertius** [SageTertius/SS_X3_Reports#52]
UBA Written Report
Report Name: YFECL
Report Link : https://github.com/SageTertius/SS_X3_Reports/blob/master/Report%20Templates/HR%20Confirm/Former%20Employer%20Cover%20Letter_YFECL.rpt
Comment: Uploaded to github yet to be uploaded to UBA envt.

**Comment by KaltwasserAlma** [comment]
Recreate Report

**Comment by KaltwasserAlma** [comment]
Already written by Hershlin

**Comment by hershlin** [comment]
Uploaded

**Comment by hershlin** [comment]
Completed and Checked. Reassigned to Alma

**Comment by KaltwasserAlma** [comment]
Recreate report. Tested in X3

**Comment by KaltwasserAlma** [comment]
Uploaded to UAT
