### ISSUE TITLE
Confirmation Appraisal Report

### ISSUE THREAD

**Issue by SageTertius** [SageTertius/SS_X3_Reports#58]
UBA Written Report
Report Name: YCDR
Report Link : https://github.com/SageTertius/SS_X3_Reports/blob/master/Report%20Templates/HR%20Confirm/Confirmation%20Appraisal%20Letter_YCAL.rpt
Comment: None

**Comment by KaltwasserAlma** [comment]
Recreate Report

**Comment by hershlin** [comment]
Uploaded
