### ISSUE TITLE
Letter Of Resignation (Indebtedness & Benefit) - YTERMACCIND

### ISSUE THREAD

**Issue by SageTertius** [SageTertius/SS_X3_Reports#62]
UBA Written Report
Report Name:YLRI&B
Report Link : https://github.com/SageTertius/SS_X3_Reports/blob/master/Report%20Templates/HR%20Exit/Letter%20of%20Resignation%20(indebtedness%20%26%20benefit)_YLRI%26B.rpt
Comment:

**Comment by KaltwasserAlma** [comment]
Redu Repot

**Comment by KaltwasserAlma** [comment]
Uploaded to UAT
