### ISSUE TITLE
Terminal Account - Benefit - YTERMACCBEN

### ISSUE THREAD

**Issue by SageTertius** [SageTertius/SS_X3_Reports#63]
UBA Written Report
Report Name: YTAB
Report Link : https://github.com/SageTertius/SS_X3_Reports/blob/master/Report%20Templates/HR%20Exit/Terminal%20Account%20Benefit_YTAB.rpt
Comment: Yet to be uploaded to UBA envt.

**Comment by KaltwasserAlma** [comment]
Recreate report

**Comment by KaltwasserAlma** [comment]
Already written by Hershlin

**Comment by hershlin** [comment]
Uploaded

**Comment by hershlin** [comment]
Completed and Checked. Reassigned to Alma

**Comment by KaltwasserAlma** [comment]
Uploaded to UAT

**Comment by carldek** [comment]
Spelling mistake 
![image](https://user-images.githubusercontent.com/33486936/36470041-22948436-16f2-11e8-8bd6-13b785d07063.png)
