### ISSUE TITLE
Terminal Account - Indebtedness - YTERMACCIND

### ISSUE THREAD

**Issue by SageTertius** [SageTertius/SS_X3_Reports#64]
UBA Written Report
Report Name: YTAI
Report Link : https://github.com/SageTertius/SS_X3_Reports/blob/master/Report%20Templates/HR%20Exit/Terminal%20Account%20Indeptedness_YTAI.rpt
Comment: Yet to be uploaded on UBA envt.

**Comment by KaltwasserAlma** [comment]
Recreate report

**Comment by KaltwasserAlma** [comment]
Already written by Hershlin

**Comment by hershlin** [comment]
Uploaded

**Comment by hershlin** [comment]
Completed and Checked. Reassigned to Alma

**Comment by KaltwasserAlma** [comment]
Uploaded to UAT

**Comment by carldek** [comment]
Duplicate
