### ISSUE TITLE
Letter Of Caution - YSANC002

### ISSUE THREAD

**Issue by SageTertius** [SageTertius/SS_X3_Reports#7]
Example Link: https://github.com/SageTertius/SS_X3_Reports/blob/master/Report%20Examples/Work%20Ethics/Email%20formats%20for%20WEorkplace%20Ethics%20module_v2.doc
Example Page No:  2
Report Name: YSANC002
Parameters: EmployeeID (REFNUM), SanctionNo (SANNBR)
Report Template Link:
https://github.com/SageTertius/SS_X3_Reports/blob/master/Report%20Templates/Work%20Ethics/YDISSUMTEMP.rpt
Comments: Sanction Sub Report

**Comment by Quintonsmithy** [comment]
Re-open for Alma to change View

**Comment by RiaanWilk** [comment]
Testing done on UBA

**Comment by carldek** [comment]
testing complete
